# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [workflow-test]
  pull_request:
    branches: [workflow-test]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: NODE_ENV=development npm run strapi build

      - name: Start project
        env:
          PORT: "1337"
          HOST: "127.0.0.1"
          CLOUDINARY_SECRET: ${{secrets.CLOUDINARY_SECRET_DEV}}
          CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME_DEV}}
          CLOUDINARY_KEY: ${{secrets.CLOUDINARY_KEY_DEV}}
        run: pm2 start ecosystem.config.js
      - run: pm2 reload workflow
