# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [workflow-test]
  pull_request:
    branches: [workflow-test]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Build project
        env: |
          CLOUDINARY_SECRET_DEV: ${{secrets.CLOUDINARY_SECRET_DEV}}
          CLOUDINARY_NAME_DEV: ${{secrets.CLOUDINARY_NAME_DEV}}
          CLOUDINARY_KEY_DEV: ${{secrets.CLOUDINARY_KEY_DEV}}
        run: NODE_ENV=development yarn build
      - run: pm2 start ecosystem.config.js
      - run: pm2 reload workflow
